# Generated by Django 3.1.7 on 2021-04-18 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('typeUser', models.CharField(max_length=10)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='images/user/')),
                ('creationTime', models.DateTimeField(null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('token_used_to_active', models.CharField(blank=True, max_length=30, null=True)),
                ('companyName', models.CharField(blank=True, max_length=15, null=True)),
                ('customUserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
