# Generated by Django 3.1.7 on 2021-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0002_auto_20210418_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gitAccount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gitFace',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gitInsta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='gitLinked',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
