# Generated by Django 3.1.7 on 2021-04-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0003_auto_20210422_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fieldCompany',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='locationUser',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
