# Generated by Django 3.1.7 on 2021-04-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsers', '0004_auto_20210422_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='locationUser',
            new_name='location',
        ),
    ]
