# Generated by Django 3.1.7 on 2021-04-18 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadCer', models.FileField(upload_to='files/certificate/')),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('jobType', models.CharField(choices=[('P', 'Part Time'), ('F', 'Full Time')], max_length=1)),
                ('description', models.TextField(max_length=100)),
                ('published_at', models.DateTimeField()),
                ('vacancy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('salary', models.FloatField(blank=True, null=True)),
                ('experience', models.CharField(max_length=50)),
                ('aplayingNum', models.IntegerField()),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('benefits', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJob.category')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsers.users')),
            ],
        ),
        
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='aplayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('uploadCV', models.FileField(upload_to='files/cv/')),
                ('aplay_at', models.DateTimeField()),
                ('isAccept', models.BooleanField(default=False)),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJob.jobs')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsers.users')),
            ],
            options={
                'unique_together': {('userID', 'jobID')},
            },
        ),
        migrations.CreateModel(
            name='tagsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJob.jobs')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJob.tags')),
            ],
            options={
                'unique_together': {('tagID', 'jobID')},
            },
        ),
        migrations.CreateModel(
            name='aplayCer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplayID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJob.aplayuser')),
                ('cerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJob.certificate')),
            ],
            options={
                'unique_together': {('cerID', 'aplayID')},
            },
        ),
    ]
