# Generated by Django 3.1.7 on 2021-04-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppJob', '0002_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppJob.locations'),
        ),
    ]
