# Generated by Django 3.1.7 on 2021-04-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJob', '0003_auto_20210418_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplayuser',
            name='coverLitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aplayuser',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
