# Generated by Django 3.1.7 on 2021-04-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJob', '0005_auto_20210425_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplayuser',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
