# Generated by Django 3.1.7 on 2021-04-23 05:27

import AppBlog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimg',
            name='blogimg',
            field=models.ImageField(upload_to=AppBlog.models.upload_path),
        ),
    ]
