# Generated by Django 3.1.7 on 2021-05-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_likesblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='numLike',
            field=models.IntegerField(default=0),
        ),
    ]
