# Generated by Django 3.1.7 on 2021-04-07 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_blogimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imgID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppBlog.blogimg'),
        ),
    ]
