# Generated by Django 3.1.7 on 2021-04-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_blog_imgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imgID',
        ),
        migrations.DeleteModel(
            name='blogImg',
        ),
    ]
