# Generated by Django 3.1.7 on 2021-04-07 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_auto_20210408_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogimg', models.ImageField(upload_to='images/blog/')),
                ('blogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.blog')),
            ],
        ),
    ]
